default:
    @just --list --unsorted

start:
    docker-compose up -d

stop:
    docker-compose down

restart:
    docker-compose restart

update:
    #!/usr/bin/env bash
    set -euo pipefail
    docker-compose pull
    docker-compose up -d

logs:
    docker-compose logs
