import subprocess
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader

# Paths
SCRIPT_DIR = Path(__file__).parent
CONFIG_FILE = SCRIPT_DIR / "config.yaml"
TEMPLATE_FILE = SCRIPT_DIR / "lab-proxy.conf.j2"
OUTPUT_FILE = Path("/opt/homebrew/etc/nginx/servers/lab-proxy.conf")
# OUTPUT_FILE = SCRIPT_DIR / "lab-proxy.conf"

# Load config
config = yaml.safe_load(CONFIG_FILE.read_text())

# Render template
env = Environment(loader=FileSystemLoader(SCRIPT_DIR), trim_blocks=True, lstrip_blocks=True)
template = env.get_template(TEMPLATE_FILE.name)

output = ["# Generated by setup.py - DO NOT EDIT MANUALLY\n"]
for service in config["services"]:
    output.append(template.render(
        service=service,
        base_domain=config["base_domain"],
        authelia_domain=config["authelia_domain"],
        authelia_verify_url=config["authelia_verify_url"],
        authelia_verify_path=config["authelia_verify_path"]
    ))

# Write config
OUTPUT_FILE.write_text("\n".join(output))
print(f"✓ Generated config with {len(config['services'])} services")

# Test and restart
if subprocess.run(["nginx", "-t"]).returncode != 0:
    sys.exit(1)

subprocess.run(["brew", "services", "restart", "nginx"])
print("✓ Done")