services:
  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9004:8080"
    env_file: ./.env
    configs:
    - source: searxng_settings
      target: /etc/searxng/settings.yml

configs:
  searxng_settings:
    content: |
      use_default_settings: true
      search:
        formats:
          - html
          - json