services:
  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9004:8080"
    env_file: ./.env
    configs:
    - source: searxng_settings
      target: /etc/searxng/settings.yml

configs:
  searxng_settings:
    content: |
      use_default_settings:
        engines:
          remove:
            - duckduckgo
            - duckduckgo images
            - duckduckgo videos
            - duckduckgo news

      search:
        formats:
          - html
          - json

      engines:
        - name: braveapi
          engine: braveapi
          api_key: "${SEARXNG_BRAVE_API_KEY}"
          results_per_page: 20
          inactive: false
        - name: bing
          disabled: false